export const data = {
    lose_weight: [
        { label: 'Legs', value: 'Legs' },
        { label: 'Arms', value: 'Arms' },
        { label: 'Shoulders', value: 'Shoulders' },
        { label: 'Back', value: 'Back' },
        { label: 'Chest', value: 'Chest' },
        { label: 'Abs', value: 'Abs' },
        { label: 'Full Body', value: 'Full Body' },
    ],
    stay_fit: [
        { label: 'Chest', value: 'Chest' },
        { label: 'Abs', value: 'Abs' },
        { label: 'Full Body', value: 'Full Body' },
    ],
    get_stronger: [
        { label: 'Legs', value: 'Legs' },
        { label: 'Arms', value: 'Arms' },
        { label: 'Shoulders', value: 'Shoulders' },
        { label: 'Back', value: 'Back' },
        { label: 'Grip', value: 'Grip' },
        { label: 'Core', value: 'Core' },
        { label: 'Full Body', value: 'Full Body' },
    ],
    improve_cardio: [
        { label: 'Cycling', value: 'Cycling' },
        { label: 'Running', value: 'Running' },
        { label: 'Walking', value: 'Walking' },
        { label: 'Stairs', value: 'Stairs' },
        { label: 'Rowing', value: 'Rowing' },
    ],
    increase_muscle_mass: [
        { label: 'Legs', value: 'Legs' },
        { label: 'Arms', value: 'Arms' },
        { label: 'Shoulders', value: 'Shoulders' },
        { label: 'Back', value: 'Back' },
        { label: 'Chest', value: 'Chest' },
        { label: 'Abs', value: 'Abs' },
        { label: 'Full Body', value: 'Full Body' },
    ],
    tone_and_sculpt: [
        { label: 'Abdomen', value: 'Abdomen' },
        { label: 'Thighs', value: 'Thighs' },
        { label: 'Glutes', value: 'Glutes' },
        { label: 'Arms', value: 'Arms' },
        { label: 'Shoulders', value: 'Shoulders' },
        { label: 'Back', value: 'Back' },
        { label: 'Calves', value: 'Calves' },
        { label: 'Core', value: 'Core' },
        { label: 'Chest', value: 'Chest' },
        { label: 'Full Body', value: 'Full Body' },
    ],
    prepare_for_event: [
        { label: 'Marathon', value: 'Marathon' },
        { label: 'Sprint', value: 'Sprint' },
        { label: 'Powerlifting', value: 'Powerlifting' },
        { label: 'Triathlon', value: 'Triathlon' },
        { label: 'Basketball', value: 'Basketball' },
    ],
    rehabilitate_after_injury: [
        { label: 'Knees', value: 'Knees' },
        { label: 'Shoulder', value: 'Shoulder' },
        { label: 'Back', value: 'Back' },
        { label: 'Ankle', value: 'Ankle' },
        { label: 'Wrist', value: 'Wrist' },
        { label: 'Hips', value: 'Hips' },
        { label: 'Neck', value: 'Neck' },
        { label: 'Elbow', value: 'Elbow' },
    ],
    learn_movement: [
        { label: 'Pull-up', value: 'Pull-up' },
        { label: 'Muscle Up', value: 'Muscle Up' },
        { label: 'Handstand', value: 'Handstand' },
    ]
};
